insert into event (id, name, rating, price) VALUES (0, 'Dead Pool', 3, 80.0);
insert into event (id, name, rating, price) VALUES (1, 'Pulp Fiction', 2, 100.0);
insert into event (id, name, rating, price) VALUES (2, 'Birdman', 2, 100.0);
insert into event (id, name, rating, price) VALUES (3, 'Selma', 2, 100.0);
insert into event (id, name, rating, price) VALUES (4, 'Inherent Vice', 2, 100.0);
insert into event (id, name, rating, price) VALUES (5, 'Foxcatcher', 2, 100.0);
insert into event (id, name, rating, price) VALUES (6, 'Whiplash', 2, 100.0);
insert into event (id, name, rating, price) VALUES (7, 'The Duke of Burgundy', 2, 100.0);
insert into event (id, name, rating, price) VALUES (8, 'It Follows', 2, 100.0);
insert into event (id, name, rating, price) VALUES (9, 'Still Alice', 2, 100.0);
insert into event (id, name, rating, price) VALUES (10, 'The Tale of Princess Kaguya', 2, 100.0);
insert into event (id, name, rating, price) VALUES (11, 'Mad Max: Fury Road', 2, 100.0);
insert into event (id, name, rating, price) VALUES (12, 'Inside Out', 2, 100.0);
insert into event (id, name, rating, price) VALUES (13, 'Listen Up Philip', 2, 100.0);
insert into event (id, name, rating, price) VALUES (14, 'Slow West', 2, 100.0);
insert into event (id, name, rating, price) VALUES (15, 'Song of the Sea', 2, 100.0);
insert into event (id, name, rating, price) VALUES (16, 'The Wonders', 2, 100.0);
insert into event (id, name, rating, price) VALUES (17, 'Hard to Be a God', 2, 100.0);
insert into event (id, name, rating, price) VALUES (18, '45 Years', 2, 100.0);
insert into event (id, name, rating, price) VALUES (19, 'Macbeth', 2, 100.0);
insert into event (id, name, rating, price) VALUES (20, 'Carol', 2, 100.0);
insert into event (id, name, rating, price) VALUES (21, 'The Forbidden Room', 3, 100.0);
insert into event (id, name, rating, price) VALUES (22, 'Batman vs Superman', 3, 130.0);
insert into event (id, name, rating, price) VALUES (23, 'Warcraft', 3, 140.0);
insert into event (id, name, rating, price) VALUES (24, 'Avengers: Age of Ultron', 3, 100.0);
insert into event (id, name, rating, price) VALUES (25, 'Transformers: Age of Distinction', 3, 100.0);
insert into event (id, name, rating, price) VALUES (26, 'Jurassic World', 3, 100.0);
insert into event (id, name, rating, price) VALUES (27, 'Minions', 3, 100.0);
insert into event (id, name, rating, price) VALUES (28, 'Terminator Genisys', 3, 100.0);
insert into event (id, name, rating, price) VALUES (29, 'Fifty Shades of Grey', 3, 100.0);
insert into event (id, name, rating, price) VALUES (30, 'Kingsman: The Secret Service', 3, 100.0);
